export const FETCH_GAME_REQUEST = 'FETCH_GAME_REQUEST';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const FETCH_GAME_ERROR = 'FETCH_GAME_ERROR';
export const REGISTER_GAME_SUCCESS = 'REGISTER_GAME_SUCCESS';
export const REMOVE_GAME_SUCCESS = 'REMOVE_GAME_SUCCESS';
